apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t5kzimdwp-go 
  janus-idp.io/tekton: t5kzimdwp-go
  backstage.io/kubernetes-id: t5kzimdwp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t5kzimdwp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  